name: Test Build
on: [push, pull_request]

jobs:
  build:
    name: CRA Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn install
    
    - name: Run test scripts
      run: yarn build
      env:
        CI: false